/* AJ DIGITAL POINT main JavaScript */
function searchPortal(){const input=document.getElementById('portalSearch');if(!input)return;const q=input.value.trim().toLowerCase();if(!q){showMessage('कृपया Job, Form या Service का नाम लिखें।');return}const items=document.querySelectorAll('.service-box,.update-item,.info-card');let found=false;items.forEach(i=>{if(i.innerText.toLowerCase().includes(q)){i.style.outline='3px solid red';i.scrollIntoView({behavior:'smooth',block:'center'});found=true}else i.style.outline='' });if(!found)showMessage('इस नाम की Service अभी नहीं मिली।')}
function showMessage(m){const b=document.getElementById('messageBox'),t=document.getElementById('messageText');if(b&&t){t.textContent=m;b.style.display='block';setTimeout(()=>b.style.display='none',3500)}}
function closeMessage(){const b=document.getElementById('messageBox');if(b)b.style.display='none'}
document.addEventListener('DOMContentLoaded',()=>{
 const search=document.getElementById('portalSearch');if(search)search.addEventListener('keydown',e=>{if(e.key==='Enter')searchPortal()});
 document.querySelectorAll('.statewise-card').forEach(card=>{const h=card.querySelector('h3');if(!h)return;const map={'Haryana':'Haryana','Rajasthan':'Rajasthan','Punjab':'Punjab','Delhi':'Delhi','Uttar Pradesh':'Uttar_Pradesh','Bihar':'Bihar','Maharashtra':'Maharashtra','Gujarat':'Gujarat','Karnataka':'Karnataka','Madhya Pradesh':'Madhya_Pradesh','West Bengal':'West_Bengal','Tamil Nadu':'Tamil_Nadu','Andhra Pradesh':'Andhra_Pradesh','Telangana':'Telangana','Kerala':'Kerala','Jharkhand':'Jharkhand','Chhattisgarh':'Chhattisgarh','Uttarakhand':'Uttarakhand','Himachal Pradesh':'Himachal_Pradesh','Assam':'Assam','Goa':'Goa'};const key=map[h.textContent.trim()];if(!key)return;card.classList.add('state-folder-clickable');card.setAttribute('role','link');card.setAttribute('tabindex','0');const open=()=>location.href='state-services.html?state='+encodeURIComponent(key);card.addEventListener('click',e=>{if(!e.target.closest('a'))open()});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})});
 /* All Image Resizer/Image Tools links now open the upgraded tool. */
 document.querySelectorAll('a[href="image-resizer.html"],a[href="image-tools.html"]').forEach(a=>{a.href='image-tools.html'});
 document.querySelectorAll('a[href="#"]').forEach(a=>{const t=a.textContent.toLowerCase();if(t.includes('image to pdf'))a.href='image-to-pdf.html';else if(t.includes('pdf to image'))a.href='pdf-to-image.html';else if(t.includes('file size compressor'))a.href='file-size-compressor.html'});
});
